POST https://node-do-zero-h3bv.onrender.com/clients
Content-type: application/json

{
    "title": "Video 002 de node",
    "description": "Esse é o primeiro video de node",
    "duration": 100
}

###

GET https://node-do-zero-h3bv.onrender.com/clients

###

PUT https://node-do-zero-h3bv.onrender.com/videos/2a643202-0d5b-4363-a5d4-8159790df271
Content-type: application/json

{
    "title": "Video 8 de node",
    "description": "Esse é o oitavo video de teste do node",
    "duration": 100
}

###

DELETE https://node-do-zero-h3bv.onrender.com/videos/bfc7bec0-d88e-488f-8e1f-e4ddbe983f4c
